skip-invalid-config-update: true

web:
  address: 127.0.0.1
  port: 8064

alerting:
  discord:
# Test server
#    webhook-url: "https://discord.com/api/webhooks/1554894267972059136/Ar6CP5u74iYcgpV4rVKg2g9oXPj7aQn_EbiZyzYHvp2UPvR30EITuf-kKGNCPTxsCphn"
# Team server
    webhook-url: "https://discord.com/api/webhooks/1555216735643238413/V6VHp_-krvvFfUo-Ibxg5S3HgzgTWUlUWPiotzyBc7ynzwz9_ronco9rmEOIgg4IUVXf"
    title: ":helmet_with_white_cross: Chainweb Alert"


ui:
  default-sort-by: group
  title: Kadena Health Dashboard
  header: Kadena
  resolve-successful-conditions: true


default-node-health: &anchorNodeHealth
  group: A - Bootstrap nodes Health
  interval: 30s
  client:
    insecure: true
  conditions:
    - "[CONNECTED] == true"
    - "[STATUS] == 200"
    - "[CERTIFICATE_EXPIRATION] > 24h"
    - "[BODY].instance == mainnet01"
    - "has([BODY].hashes) == true"

other-node-health: &anchorOtherNodeHealth
  group: Z - Other important nodes Health
  interval: 30s
  client:
    insecure: true
  conditions:
    - "[CONNECTED] == true"
    - "[STATUS] == 200"
    - "[CERTIFICATE_EXPIRATION] > 24h"
    - "[BODY].instance == mainnet01"
    - "has([BODY].hashes) == true"


default-node up-to-date: &nodeUpToData
  group: B - Bootstrap nodes Recent Cut
  interval: 30s
  url: http://localhost:8090/age
  method: POST
  headers:
    Content-Type: application/x-www-form-urlencoded
  conditions:
    - "[STATUS] == 200"
    - "[BODY].age[0] < 300"
    - "[BODY].age[1] < 300"
    - "[BODY].age[2] < 300"
    - "[BODY].age[3] < 300"
    - "[BODY].age[4] < 300"
    - "[BODY].age[5] < 300"
    - "[BODY].age[6] < 300"
    - "[BODY].age[7] < 300"
    - "[BODY].age[8] < 300"
    - "[BODY].age[9] < 300"
    - "[BODY].age[10] < 300"
    - "[BODY].age[11] < 300"
    - "[BODY].age[12] < 300"
    - "[BODY].age[13] < 300"
    - "[BODY].age[14] < 300"
    - "[BODY].age[15] < 300"
    - "[BODY].age[16] < 300"
    - "[BODY].age[17] < 300"
    - "[BODY].age[18] < 300"
    - "[BODY].age[19] < 300"



simple-frontend: &simpleFrontend
  group: D - Frontends
  interval: 2m
  conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 24h"

discord-alert: &general-discord
  alerts:
    - type: discord
      enabled: true
      failure-threshold: 10
      minimum-reminder-interval: 24h

ping-everyone: &ping-everyone-discord
  alerts:
    - type: discord
      enabled: true
      failure-threshold: 10
      minimum-reminder-interval: 24h
      provider-override:
        message-content: "@everyone"

ping-pascal: &ping-pascal-discord
  alerts:
    - type: discord
      enabled: true
      failure-threshold: 10
      minimum-reminder-interval: 24h
      provider-override:
        message-content: "<@796003016955658261>"

ping-jose: &ping-jose-discord
  alerts:
    - type: discord
      enabled: true
      failure-threshold: 10
      minimum-reminder-interval: 24h
      provider-override:
        message-content: "<@147166876907208705>"

ping-mightchobo: &ping-mightchobo-discord
  alerts:
    - type: discord
      enabled: true
      failure-threshold: 10
      minimum-reminder-interval: 24h
      provider-override:
        message-content: "<@104387740291833856>"

ping-amir: &ping-amir-discord
  alerts:
    - type: discord
      enabled: true
      failure-threshold: 10
      minimum-reminder-interval: 24h
      provider-override:
        message-content: "<@200423297073020929>"

ping-edmund: &ping-edmund-discord
  alerts:
    - type: discord
      enabled: true
      failure-threshold: 10
      minimum-reminder-interval: 24h
      provider-override:
        message-content: "<@254760420219420672>"

ping-jumbo: &ping-jumbo-discord
  alerts:
    - type: discord
      enabled: true
      failure-threshold: 10
      minimum-reminder-interval: 24h
      provider-override:
        message-content: "<@1252248874005954562>"


endpoints:
  - name: Mnitoring Gateway
    group: "0 - Monitoring Gateway"
    url: http://localhost:8090/
    method: GET
    conditions:
      - "[CONNECTED] == true"
      - "[STATUS] == 200"
      - "[BODY] == OK"

  - name: pl-1 Health
    <<: [*anchorNodeHealth, *ping-everyone-discord]
    url: "https://pl-1.chainweb-community.org/chainweb/0.0/mainnet01/cut"

  - name: pl-1 Recent Blocks
    <<: [*nodeUpToData, *ping-pascal-discord]
    body: 'node=https://pl-1.chainweb-community.org'

  - name: pl-2 Health
    <<: [*anchorNodeHealth, *ping-pascal-discord]
    url: "https://pl-2.chainweb-community.org/chainweb/0.0/mainnet01/cut"

  - name: pl-2 Recent Blocks
    <<: [*nodeUpToData, *ping-pascal-discord]
    body: 'node=https://pl-2.chainweb-community.org'

  - name: nl-1 Health
    <<: [*anchorNodeHealth, *ping-pascal-discord]
    url: "https://nl-1.chainweb-community.org/chainweb/0.0/mainnet01/cut"

  - name: nl-1 Recent Blocks
    <<: [*nodeUpToData, *ping-pascal-discord]
    body: 'node=https://nl-1.chainweb-community.org'

  - name: fr-1 Health
    <<: [*anchorNodeHealth, *ping-pascal-discord]
    url: "https://fr-1.chainweb-community.org/chainweb/0.0/mainnet01/cut"

  - name: fr-1 Recent Blocks
    <<: [*nodeUpToData, *ping-pascal-discord]
    body: 'node=https://fr-1.chainweb-community.org'

  - name: ca-1 Health
    <<: [*anchorNodeHealth, *ping-pascal-discord]
    url: "https://ca-1.chainweb-community.org/chainweb/0.0/mainnet01/cut"

  - name: ca-1 Recent Blocks
    <<: [*nodeUpToData, *ping-pascal-discord]
    body: 'node=https://ca-1.chainweb-community.org'

  - name: us-e1 Health
    <<: [*anchorNodeHealth, *ping-mightchobo-discord]
    url: "https://us-e1.bootstrap.kadinic.com/chainweb/0.0/mainnet01/cut"

  - name: us-e1 Recent Blocks
    <<: [*nodeUpToData, *ping-mightchobo-discord]
    body: "node=https://us-e1.bootstrap.kadinic.com"
#

  - name: Snapshot node Health
    <<: [*anchorNodeHealth, *ping-pascal-discord]
    url: "https://54.36.120.70:4430/chainweb/0.0/mainnet01/cut"


#
  - name: Chainweb Api health
    <<: [*general-discord, *ping-everyone-discord]
    group: D - Frontends
    url: https://api.chainweb-community.org/info
    interval: 30s
    conditions:
      - "[CONNECTED] == true"
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 24h"
      - "[BODY].nodeVersion == mainnet01"
      - "[BODY].nodePackageVersion == 3.2"
      - "has([BODY].nodeChains) == true"
#
  - name: Tools
    <<: [*simpleFrontend, *general-discord]
    url: https://tools.chainweb-community.org/

  - name: Snapshots
    <<: [*simpleFrontend, *general-discord]
    url: https://snapshots.chainweb-community.org/

  - name: Explorer
    <<: [*simpleFrontend, *general-discord]
    url: https://explorer.chainweb-community.org/mainnet


  - name: Kinesis
    <<: [*simpleFrontend, *general-discord]
    url: https://kinesis.kda-chain.org/

  - name: Denascan
    <<: [*simpleFrontend, *general-discord]
    url: https://denascan.com/


  - name: X-chain Gas stations
    <<: [*general-discord, *ping-everyone-discord]
    group: C - Pact
    url: http://localhost:8090/pact
    interval: 10m
    method: POST
    headers:
      Content-Type: application/json
    body: '{"chains":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19],"cmd":"(>= (coin.get-balance \"kadena-xchain-gas\") 0.5)"}'
    conditions:
      - "[STATUS] == 200"
      - "[BODY].results[0] == true"
      - "[BODY].results[1] == true"
      - "[BODY].results[2] == true"
      - "[BODY].results[3] == true"
      - "[BODY].results[4] == true"
      - "[BODY].results[5] == true"
      - "[BODY].results[6] == true"
      - "[BODY].results[7] == true"
      - "[BODY].results[8] == true"
      - "[BODY].results[9] == true"
      - "[BODY].results[10] == true"
      - "[BODY].results[11] == true"
      - "[BODY].results[12] == true"
      - "[BODY].results[13] == true"
      - "[BODY].results[14] == true"
      - "[BODY].results[15] == true"
      - "[BODY].results[16] == true"
      - "[BODY].results[17] == true"
      - "[BODY].results[18] == true"
      - "[BODY].results[19] == true"
#
  - name: Pact Current Time
    <<: [*general-discord,*ping-everyone-discord]
    group: C - Pact
    url: http://localhost:8090/pact
    method: POST
    headers:
      Content-Type: application/json
    body: '{"chains":[0], "cmd":"(<= (diff-time (time \"$$current_time\") (free.util-time.now)) 300.0)"}'
    conditions:
      - "[STATUS] == 200"
      - "[BODY].results[0] == true"

  - name: Mercatus Frontend
    <<: [*general-discord, *ping-amir-discord]
    group: G - Mercatus
    url: https://mercatus.works
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 24h"
#
  - name: Mercatus Backend
    <<: [*general-discord, *ping-pascal-discord]
    group: G - Mercatus
    url: https://dexapi.kadena.fun/info
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 24h"
      - "[BODY].status == RUNNING"

  - name: Hyperlane Backend
    <<: *general-discord
    group: E - Hyperlane
    url: https://hyperlane-status.chainweb-community.org/
    interval: 2m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 24h"
#
  - name: Relayer gas - Kadena
    <<: [*general-discord, *ping-everyone-discord]
    group: E - Hyperlane
    url: http://localhost:8090/pact
    method: POST
    headers:
      Content-Type: application/json
    body: '{"chains":[2],"cmd":"(* 1000.0 (coin.get-balance \"r:n_e595727b657fbbb3b8e362a05a7bb8d12865c1ff.relayers\"))"}'
    conditions:
      - "[STATUS] == 200"
      - "[BODY].results[0] > 1000"


  - name: Relayer gas - Ethereum
    <<: [*general-discord, *ping-everyone-discord]
    group: E - Hyperlane
    ui:
      resolve-successful-conditions: true
    url: http://localhost:8090/eth_balance_gwei
    method: POST
    headers:
      Content-Type: application/x-www-form-urlencoded
    body: 'address=0x02198cC71835baAe1b1B295eb49BB8365AC237e6'
    conditions:
      - "[STATUS] == 200"
      - "[BODY].balance > 0"
      - "[BODY].balance > 4000000"

  - name: Hyperlane Backend Status
    <<: [*general-discord, *ping-everyone-discord]
    group: E - Hyperlane
    url: https://hyperlane-status.chainweb-community.org/admin-actions/bridge-status/mainnet
    interval: 2m
    conditions:
      - "[STATUS] == 200"
      - "[BODY].data.kda.paused == false"
      - "[BODY].data.evm.paused == false"
#
  - name: Hyperlane Signer Alcantara
    <<: [*general-discord, *ping-pascal-discord]
    group: E - Hyperlane
    url: https://raw.githubusercontent.com/kinesis-bridge/kinesis-signatures/refs/heads/main/summary.json
    interval: 2m
    conditions:
       - "[STATUS] == 200"
       - "[BODY].validators.kadena.alcantara.ok == true"
       - "[BODY].validators.eth.alcantara.ok == true"
#
  - name: Hyperlane Signer huajiang
    <<: [*general-discord, *ping-pascal-discord]
    group: E - Hyperlane
    url: https://raw.githubusercontent.com/kinesis-bridge/kinesis-signatures/refs/heads/main/summary.json
    interval: 2m
    conditions:
       - "[STATUS] == 200"
       - "[BODY].validators.kadena.huajiang.ok == true"
       - "[BODY].validators.eth.huajiang.ok == true"
#
  - name: Hyperlane Signer mackinac
    <<: [*general-discord, *ping-pascal-discord]
    group: E - Hyperlane
    url: https://raw.githubusercontent.com/kinesis-bridge/kinesis-signatures/refs/heads/main/summary.json
    interval: 2m
    conditions:
       - "[STATUS] == 200"
       - "[BODY].validators.kadena.mackinac.ok == true"
       - "[BODY].validators.eth.mackinac.ok == true"
#

suites:
  - name: Kinesis kb-ETH Collateral

    group: F - Kinesis
    interval: 5m
    endpoints:
      - name: Kinesis kb-ETH Reserve
        <<: *general-discord
        method: POST
        ui:
          resolve-successful-conditions: true
        url: http://localhost:8090/eth_balance_gwei
        headers:
          Content-Type: application/x-www-form-urlencoded
        body: 'address=0xbddB58bF21b12D70eED91b939Ae061572010B11d'
        conditions:
          - "[STATUS] == 200"
          - "[BODY].balance != 0.0"
        store:
          reserve: "[BODY].balance"

      - name: Kinesis kb-ETH Supply < Reserve
        <<: *ping-everyone-discord
        url: http://localhost:8090/pact
        ui:
          resolve-successful-conditions: true
        method: POST
        headers:
          Content-Type: application/json
        body: '{"chains":[2],"cmd":"(use free.util-math)(use n_e595727b657fbbb3b8e362a05a7bb8d12865c1ff.kb-ETH)(round (* 1000000000.0  (sum (map (at \"balance\") (select accounts (where \"balance\" (< 0.0) ))))) 0)"}'
        conditions:
          - "[STATUS] == 200"
          - "[BODY].results[0] < [CONTEXT].reserve"

  - name: Kinesis kb-USDC Collateral

    group: F - Kinesis
    interval: 5m
    endpoints:
      - name: Kinesis kb-USDC Reserve
        <<: *general-discord
        method: POST
        ui:
          resolve-successful-conditions: true
        url: http://localhost:8090/erc_20_balance

        headers:
          Content-Type: application/x-www-form-urlencoded
        body: 'token=0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48&address=0x81C2813aa88F66bca1e55838045Aaceb72FEbFc1'
        conditions:
          - "[STATUS] == 200"
          - "[BODY].balance != 0.0"
        store:
          reserve: "[BODY].balance"

      - name: Kinesis kb-USDC Supply < Reserve
        <<: *ping-everyone-discord
        url: http://localhost:8090/pact
        ui:
          resolve-successful-conditions: true
        method: POST
        headers:
          Content-Type: application/json
        body: '{"chains":[2],"cmd":"(use free.util-math)(use n_e595727b657fbbb3b8e362a05a7bb8d12865c1ff.kb-USDC)(round (* 1000000.0  (sum (map (at \"balance\") (select accounts (where \"balance\" (< 0.0) ))))) 0)"}'
        conditions:
          - "[STATUS] == 200"
          - "[BODY].results[0] < [CONTEXT].reserve"


  - name: Hyperlane Message Dispatch Eth to KDA (not Fatal)
    group: E - Hyperlane
    interval: 30m
    endpoints:
      - name: Hyperlane Eth MailBox Last-Dispatch-ID
        <<: *general-discord
        group: F - Kinesis
        method: POST
        ui:
          resolve-successful-conditions: true
        url: http://localhost:8090/latest_dispatch_id

        headers:
          Content-Type: application/x-www-form-urlencoded
        body: 'address=0x82A729A4c7B2aeBDdbFCCF533e7B75c61c45c23c'
        conditions:
          - "[STATUS] == 200"
          - "has([BODY].id) == true"
        store:
          latest_id: "[BODY].id"

      - name: KDA Dispatch ID delivery
        <<: *general-discord
        group: F - Kinesis
        url: http://localhost:8090/pact
        ui:
          resolve-successful-conditions: true
        method: POST
        headers:
          Content-Type: application/json
        body: '{"chains":[2],"cmd":"(n_e595727b657fbbb3b8e362a05a7bb8d12865c1ff.mailbox.delivered (int-to-str 64 (str-to-int 16 \"[CONTEXT].latest_id\")))"}'
        conditions:
          - "[STATUS] == 200"
          - "[BODY].results[0] == true"

  - name: Hyperlane Message Dispatch KDA to Eth (not Fatal)
    group: E - Hyperlane
    interval: 30m
    endpoints:
      - name:  Hyperlane KDA MailBox Last-Dispatch-ID
        <<: *general-discord
        url: http://localhost:8090/pact
        ui:
          resolve-successful-conditions: true
        method: POST
        headers:
          Content-Type: application/json
        body: '{"chains":[2],"cmd":"(use n_e595727b657fbbb3b8e362a05a7bb8d12865c1ff.mailbox)(int-to-str 16 (str-to-int 64 (at \"latest-dispatched-id\" (read contract-state \"default\"))))"}'
        conditions:
          - "[STATUS] == 200"
          - "has([BODY].results[0]) == true"
          - "[BODY].results[0] != ''"
        store:
          latest_id: "[BODY].results[0]"

      - name:  Eth Dispatch ID delivery
        <<: *general-discord
        method: POST
        ui:
          resolve-successful-conditions: true
        url: http://localhost:8090/mailbox_delivered
        headers:
          Content-Type: application/x-www-form-urlencoded
        body: 'address=0x82A729A4c7B2aeBDdbFCCF533e7B75c61c45c23c&id=[CONTEXT].latest_id'
        conditions:
          - "[STATUS] == 200"
          - "[BODY].delivered == true"
